task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='labels'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views

urlpatterns = [
    path('', views.BaseView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('i18n/', include('django.conf.urls.i18n')),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
]

task_manager/labels/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(_('Name'), max_length=100, null=False, unique=True)
    created_at = models.DateTimeField(_('Created date'), default=timezone.now)

    def get_absolute_url(self):
        return reverse('labels:labels')

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(_('Name'), max_length=100, unique=True)
    created_at = models.DateTimeField(_('Created date'), default=timezone.now)

    def get_absolute_url(self):
        return reverse('statuses:statuses')

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


class Task(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    description = models.TextField(_('Description'), null=True)
    status = models.ForeignKey(
        Status,
        related_name='statuses',
        on_delete=models.PROTECT,
        verbose_name=_('Status'),
        null=False
    )
    labels = models.ManyToManyField(Label, verbose_name=_('Labels'), blank=True)
    author = models.ForeignKey(
        User,
        related_name='authors',
        verbose_name=_('Author'),
        on_delete=models.PROTECT
    )
    executor = models.ForeignKey(
        User,
        related_name='executors',
        on_delete=models.PROTECT,
        verbose_name=_('Executor'),
        blank=True,
        null=False
    )
    created_at = models.DateTimeField(_('Created date'), default=timezone.now)

    def get_absolute_url(self):
        return reverse('tasks:tasks')

    def __str__(self):
        return self.name

task_manager/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    first_name = models.CharField(_("first name"), max_length=150, blank=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False)

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_absolute_url(self):
        return reverse('users:users')

    def __str__(self):
        return self.get_full_name()

task_manager/labels/forms.py
from django.forms import ModelForm
from task_manager.labels.models import Label


class LabelForm(ModelForm):

    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm
from task_manager.statuses.models import Status


class StatusForm(ModelForm):

    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django.forms import ModelForm
from task_manager.tasks.models import Task


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'labels', 'executor']

task_manager/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2',
        ]

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.utils.translation import gettext_lazy as _
from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.tasks.models import Task
from task_manager.utils import NoPermissionMixin


class LabelListView(NoPermissionMixin, LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/labels.html'


class LabelCreateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label created successfully!')


class LabelDeleteView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    success_url = reverse_lazy('labels:labels')
    template_name = 'labels/delete.html'
    success_message = _('Label deleted successfully!')

    def form_valid(self, form):
        if Task.objects.filter(labels=self.object):
            messages.error(
                self.request,
                _("It is not possible to delete a label because it is in use")
            )
            return redirect(self.success_url)
        return super().form_valid(form)


class LabelUpdateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label updated successfully!')

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.utils.translation import gettext_lazy as _
from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status
from task_manager.tasks.models import Task
from task_manager.utils import NoPermissionMixin


class StatusListView(NoPermissionMixin, LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/statuses.html'


class StatusCreateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status created successfully!')


class StatusDeleteView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Status
    success_url = reverse_lazy('statuses:statuses')
    template_name = 'statuses/delete.html'
    success_message = _('Status deleted successfully!')

    def form_valid(self, form):
        if Task.objects.filter(status=self.object):
            messages.error(
                self.request,
                _("It is not possible to delete a status because it is in use")
            )
            return redirect(self.success_url)
        return super().form_valid(form)


class StatusUpdateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/update.html'
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status updated successfully!')

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView
from django.utils.translation import gettext_lazy as _
from django_filters.views import FilterView

from task_manager.constants import ERROR_MESSAGE, ERROR_URL
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task
from task_manager.utils import NoPermissionMixin


class TaskListView(NoPermissionMixin, LoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks.html'
    filterset_class = TaskFilter


class TaskCreateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task created successfully!')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'


class TaskDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    SuccessMessageMixin,
    DeleteView
):
    model = Task
    success_url = reverse_lazy('tasks:tasks')
    template_name = 'tasks/delete.html'
    success_message = _('Task deleted successfully!')

    def test_func(self):
        return self.get_object().author == self.request.user or self.request.user.is_superuser

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(self.request, ERROR_MESSAGE)
            return redirect(ERROR_URL)
        messages.error(self.request, _("Task can be deleted only by its author."))
        return redirect(self.success_url)


class TaskUpdateView(NoPermissionMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task updated successfully!')

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from task_manager.tasks.models import Task
from task_manager.users.forms import UserForm
from django.utils.translation import gettext_lazy as _


ERROR_URL = reverse_lazy('users:users')
ERROR_MESSAGE = _('You have no permission to delete another user.')


class UserListView(ListView):
    model = get_user_model()
    template_name = 'users/users.html'


class UserCreateView(SuccessMessageMixin, CreateView):
    model = get_user_model()
    form_class = UserForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('login')
    success_message = _('User registered successfully!')


class UserDeleteView(SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    model = get_user_model()
    success_url = reverse_lazy('users:users')
    template_name = 'users/delete.html'
    success_message = _('User deleted successfully!')

    def test_func(self):
        return self.get_object().id == self.request.user.pk

    def handle_no_permission(self):
        messages.error(
            self.request,
            _('You have no permission to delete another user.')
        )
        return redirect(self.success_url)

    def form_valid(self, form):
        if Task.objects.filter(author_id=self.request.user.pk):
            messages.error(
                self.request,
                _("It is not possible to delete a user because it is in use")
            )
            return redirect(self.success_url)
        return super().form_valid(form)


class UserUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = UserForm
    template_name = 'users/update.html'
    success_message = _('User updated successfully!')

    def test_func(self):
        return self.get_object().id == self.request.user.pk or self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(
            self.request,
            _('You have no permission to update another user.')
        )
        return redirect(ERROR_URL)

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _


class BaseView(TemplateView):
    template_name = 'index.html'


class LoginUserView(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    next_page = 'index'
    success_message = _('You are logged in!')


class LogoutUserView(SuccessMessageMixin, LogoutView):

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.info(self.request, _('You are logged out!'))
        return response

task_manager/templates/tasks/create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form class="form" method="post">
    <h1 class="my-4">{% translate "Create task" %}</h1>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-info" type="submit">{% translate "Create" %}</button>
    {% endbuttons %}
</form>
{% endblock content %}

task_manager/templates/tasks/delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate "Deleting task" %}</h1>
<p>{% translate "Are you sure you want to delete" %} {{ task }}?</p>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}
{% translate "Task" %}
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header bg-info text-white">
        <h2>{{ task.name }}</h2>
    </div>
    <div class="card-body bg-light">
        <p>{{ task.description }}</p>
        <hr>
        <div class="container">
            <div class="row align-items-start">
                <div class="col">
                    {% translate 'Author' %}:
                </div>
                <div class="col">
                    {{ task.author }}
                </div>
            </div>
            <div class="row align-items-start">
                <div class="col">
                    {% translate 'Executor' %}:
                </div>
                <div class="col">
                    {{ task.executor }}
                </div>
            </div>
            <div class="row align-items-start">
                <div class="col">
                    {% translate 'Status' %}:
                </div>
                <div class="col">
                    {{ task.status }}
                </div>
            </div>
            <div class="row align-items-start">
                <div class="col">
                    {% translate 'Created date' %}:
                </div>
                <div class="col">
                    {{ task.created_at }}
                </div>
            </div>
            <div>
                {% translate 'Labels' %}:
                <ul>
                    {% for label in task.labels.all %}
                    <li>{{ label.name }}</li>
                    {% endfor %}
                </ul>
            </div>
            <a href="{% url 'tasks:update' task.id %}">{% translate "Update" %}</a>
            <br>
            <br>
            <a href="{% url 'tasks:delete' task.id %}">{% translate "Delete" %}</a>
        </div>
{% endblock %}

task_manager/templates/tasks/tasks.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}


{% block header %}
{% translate "Tasks" %}
{% endblock %}

{% block content %}
<a class="nav-link" href="{% url 'tasks:create' %}">{% translate "Create task" %}</a>
<form method="get">
    {% bootstrap_form filter.form %}
    {% buttons %}
    <button class="btn btn-info" type="submit">{% translate "Show" %}</button>
    {% endbuttons %}
</form>
<table class="table table-striped">
    <thead>
    <tr>
        <th>{% translate "ID" %}</th>
        <th>{% translate "Name" %}</th>
        <th>{% translate "Status" %}</th>
        <th>{% translate "Author" %}</th>
        <th>{% translate "Executor" %}</th>
        <th>{% translate "Created date" %}</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for task in object_list %}
    <tr>
        <td>{{ task.id }}</td>
        <td>
            <a href="{% url 'tasks:detail' task.id %}">{{ task.name }}</a>
        </td>
        <td>{{ task.status }}</td>
        <td>{{ task.author.get_full_name }}</td>
        <td>{{ task.executor.get_full_name }}</td>
        <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
        <td>
            <a href="{% url 'tasks:update' task.id %}">{% translate "Update" %}</a>
            <br>
            <br>
            <a href="{% url 'tasks:delete' task.id %}">{% translate "Delete" %}</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<form class="form" method="post">
    <h1 class="my-4">{% translate "Updating task" %}</h1>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-info" type="submit">{% translate "Update" %}</button>
    {% endbuttons %}
</form>
{% endblock content %}